"""
Human Escalation & Legal Referral Engine Guardrail
Dispatches verified escalation referrals to human legal counsel, pro bono advocates, and government portals when automated confidence is low or emergency triggers fire.
"""

from typing import Dict, Any, List

class EscalationGuard:
    OFFICIAL_REFERRAL_CHANNELS = {
        "CYBER_EMERGENCY": {
            "authority": "National Cyber Crime Reporting Portal & Indian Cyber Crime Coordination Centre (I4C)",
            "helpline": "1930",
            "portal": "https://cybercrime.gov.in",
            "sla": "Within 2 Hours (Golden Hour window for account liens)",
            "action_steps": [
                "1. Immediately dial 1930 to record fraudulent transaction details.",
                "2. Note down the Financial Fraud Acknowledgment Number (Ack ID).",
                "3. Inform your bank's nodal fraud officer with the Ack ID to block debit cards and reverse transactions.",
            ]
        },
        "LEGAL_AID_INDIGENT": {
            "authority": "National Legal Services Authority (NALSA) & State Legal Services Authority (SLSA)",
            "helpline": "15100 (National Legal Aid Toll-Free Helpline)",
            "portal": "https://nalsa.gov.in",
            "sla": "24 to 48 Hours for Advocate Assignment",
            "action_steps": [
                "1. Women, children, industrial workmen, and citizens with income under statutory limits are entitled to 100% free legal aid under Section 12 of Legal Services Authorities Act, 1987.",
                "2. Dial 15100 or visit the nearest District Legal Services Authority (DLSA) office located in the District Court complex.",
                "3. Submit your case summary generated by Legal Nexus to receive a panel advocate without fees."
            ]
        },
        "CONSUMER_GRIEVANCE": {
            "authority": "National Consumer Helpline (NCH) & e-Daakhil Portal (NCDRC/DCDRC)",
            "helpline": "1915",
            "portal": "https://edaakhil.nic.in | https://consumerhelpline.gov.in",
            "sla": "Pre-litigation mediation within 30 days",
            "action_steps": [
                "1. Call 1915 to lodge a pre-litigation consumer docket.",
                "2. If unaddressed, file a direct digital consumer complaint on e-Daakhil under Section 35 CPA 2019 without requiring physical advocate presence."
            ]
        },
        "LABOUR_WAGE_DISPUTE": {
            "authority": "Office of the Chief Labour Commissioner / SAMADHAN Portal",
            "helpline": "Shram Suvidha Portal: 1800-180-1888",
            "portal": "https://samadhan.labour.gov.in",
            "sla": "15-day notice response window",
            "action_steps": [
                "1. Serve the generated 15-day statutory demand notice via Registered Post AD.",
                "2. Lodge an online conciliation dispute on the SAMADHAN portal before the Regional Labour Commissioner."
            ]
        }
    }

    @classmethod
    def evaluate_escalation(
        cls,
        grounding_score: float = 1.0,
        unverified_claims: List[str] = None,
        is_emergency: bool = False,
        urgency_type: str = None,
        domain: str = "General",
        disputed_amount: float = 0.0
    ) -> Dict[str, Any]:
        """
        Determines whether a human escalation is required and constructs the complete referral package.
        """
        unverified = unverified_claims or []
        triggers = []
        channel_key = None

        # 1. Check emergency conditions
        if is_emergency or "CYBER" in str(urgency_type).upper():
            triggers.append("Active emergency or time-sensitive critical trigger detected.")
            channel_key = "CYBER_EMERGENCY"
        elif "LABOUR" in domain.upper() or "EMPLOYMENT" in domain.upper() or "WAGE" in domain.upper():
            channel_key = "LABOUR_WAGE_DISPUTE"
        elif "CONSUMER" in domain.upper():
            channel_key = "CONSUMER_GRIEVANCE"
        else:
            channel_key = "LEGAL_AID_INDIGENT"

        # 2. Check grounding / confidence failure
        if grounding_score < 0.75 or len(unverified) > 0:
            triggers.append(f"Statutory grounding score ({grounding_score * 100:.0f}%) requires professional verification.")

        # 3. High financial quantum
        if disputed_amount and disputed_amount > 500000:
            triggers.append(f"High financial quantum (INR {disputed_amount:,.2f}) warrants human counsel representation.")

        requires_escalation = len(triggers) > 0 or is_emergency

        channel = cls.OFFICIAL_REFERRAL_CHANNELS.get(channel_key, cls.OFFICIAL_REFERRAL_CHANNELS["LEGAL_AID_INDIGENT"])

        return {
            "escalation_required": requires_escalation,
            "escalation_reasons": triggers,
            "recommended_channel": channel_key,
            "authority_name": channel["authority"],
            "helpline": channel["helpline"],
            "portal": channel["portal"],
            "sla": channel["sla"],
            "action_steps": channel["action_steps"],
            "status": "HUMAN_ESCALATION_TRIGGERED" if requires_escalation else "AUTOMATED_RESOLUTION_APPROVED"
        }
