const { ResearchNote } = require('../models');
const { sendSuccess, sendError } = require('../utils/apiResponse');

/**
 * GET /api/notebook
 * Get all notes for the authenticated user with optional filters
 */
const getNotes = async (req, res, next) => {
  try {
    const { folder, tag, search, caseId, pinned } = req.query;
    const filter = { user: req.user._id };

    if (folder) filter.folder = folder;
    if (tag) filter.tags = tag;
    if (caseId) filter.caseId = caseId;
    if (pinned === 'true') filter.isPinned = true;

    if (search && search.trim()) {
      filter.$or = [
        { title: { $regex: search.trim(), $options: 'i' } },
        { content: { $regex: search.trim(), $options: 'i' } },
        { 'clippedSources.actName': { $regex: search.trim(), $options: 'i' } },
        { 'clippedSources.section': { $regex: search.trim(), $options: 'i' } },
      ];
    }

    const notes = await ResearchNote.find(filter)
      .sort({ isPinned: -1, updatedAt: -1 })
      .populate('caseId', 'title caseNumber category');

    return sendSuccess(res, notes, 'Research notes retrieved successfully');
  } catch (error) {
    next(error);
  }
};

/**
 * POST /api/notebook
 * Create a new research note or clip statutory citation
 */
const createNote = async (req, res, next) => {
  try {
    const { title, content, folder, tags, clippedSources, caseId, isPinned, color } = req.body;

    if (!title || !title.trim()) {
      return sendError(res, 'Note title is required', 400);
    }

    const note = await ResearchNote.create({
      user: req.user._id,
      title: title.trim(),
      content: content || '',
      folder: folder?.trim() || 'General Research',
      tags: Array.isArray(tags) ? tags.map((t) => t.trim()) : [],
      clippedSources: Array.isArray(clippedSources) ? clippedSources : [],
      caseId: caseId || null,
      isPinned: Boolean(isPinned),
      color: color || '#0B1F33',
    });

    return sendSuccess(res, note, 'Research note saved successfully', 201);
  } catch (error) {
    next(error);
  }
};

/**
 * PUT /api/notebook/:id
 * Update an existing note
 */
const updateNote = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { title, content, folder, tags, clippedSources, isPinned, color } = req.body;

    const note = await ResearchNote.findOne({ _id: id, user: req.user._id });
    if (!note) {
      return sendError(res, 'Research note not found', 404);
    }

    if (title !== undefined) note.title = title.trim();
    if (content !== undefined) note.content = content;
    if (folder !== undefined) note.folder = folder.trim() || 'General Research';
    if (tags !== undefined) note.tags = Array.isArray(tags) ? tags.map((t) => t.trim()) : [];
    if (clippedSources !== undefined) note.clippedSources = clippedSources;
    if (isPinned !== undefined) note.isPinned = Boolean(isPinned);
    if (color !== undefined) note.color = color;

    await note.save();

    return sendSuccess(res, note, 'Research note updated successfully');
  } catch (error) {
    next(error);
  }
};

/**
 * DELETE /api/notebook/:id
 * Delete a note
 */
const deleteNote = async (req, res, next) => {
  try {
    const { id } = req.params;
    const note = await ResearchNote.findOneAndDelete({ _id: id, user: req.user._id });
    if (!note) {
      return sendError(res, 'Research note not found', 404);
    }

    return sendSuccess(res, { deletedId: id }, 'Research note deleted successfully');
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/notebook/folders
 * Get all unique folders with count for the authenticated user
 */
const getFolders = async (req, res, next) => {
  try {
    const folders = await ResearchNote.aggregate([
      { $match: { user: req.user._id } },
      {
        $group: {
          _id: '$folder',
          count: { $sum: 1 },
          lastUpdated: { $max: '$updatedAt' },
        },
      },
      { $sort: { _id: 1 } },
    ]);

    const formatted = folders.map((f) => ({
      name: f._id || 'General Research',
      count: f.count,
      lastUpdated: f.lastUpdated,
    }));

    return sendSuccess(res, formatted, 'Folders retrieved successfully');
  } catch (error) {
    next(error);
  }
};

/**
 * POST /api/notebook/export
 * Export selected notes as consolidated legal research brief
 */
const exportBrief = async (req, res, next) => {
  try {
    const { noteIds, title = 'Legal Research Brief' } = req.body;

    const query = { user: req.user._id };
    if (Array.isArray(noteIds) && noteIds.length > 0) {
      query._id = { $in: noteIds };
    }

    const notes = await ResearchNote.find(query).sort({ folder: 1, updatedAt: -1 });

    let markdown = `# ${title}\n\n`;
    markdown += `**Generated By:** Nyaya Setu / LegalIQ Research Intelligence\n`;
    markdown += `**Date:** ${new Date().toLocaleDateString('en-IN')}\n\n---\n\n`;

    let currentFolder = '';
    notes.forEach((n, idx) => {
      if (n.folder !== currentFolder) {
        currentFolder = n.folder;
        markdown += `## 📁 Folder: ${currentFolder}\n\n`;
      }

      markdown += `### ${idx + 1}. ${n.title}\n`;
      if (n.tags && n.tags.length > 0) {
        markdown += `*Tags:* ${n.tags.map((t) => `\`#${t}\``).join(' ')}\n\n`;
      }

      if (n.content) {
        markdown += `${n.content}\n\n`;
      }

      if (n.clippedSources && n.clippedSources.length > 0) {
        markdown += `**Clipped Legal Authorities & Statutory Sections:**\n\n`;
        n.clippedSources.forEach((cs) => {
          markdown += `- **${cs.actName} (${cs.section})**: ${cs.title || ''}\n`;
          if (cs.content) {
            markdown += `  > ${cs.content}\n`;
          }
          if (cs.citation) {
            markdown += `  *Citation:* \`${cs.citation}\`\n`;
          }
        });
        markdown += `\n`;
      }

      markdown += `---\n\n`;
    });

    return sendSuccess(res, { markdown, noteCount: notes.length }, 'Research brief exported successfully');
  } catch (error) {
    next(error);
  }
};

module.exports = {
  getNotes,
  createNote,
  updateNote,
  deleteNote,
  getFolders,
  exportBrief,
};
