/**
 * Nyaya Setu Granular Role-Based Access Control (RBAC) Permissions
 */

const PERMISSIONS = {
  // Case Permissions
  CASE_CREATE: 'case:create',
  CASE_READ_OWN: 'case:read:own',
  CASE_READ_SHARED: 'case:read:shared',
  CASE_UPDATE_OWN: 'case:update:own',
  CASE_DELETE_OWN: 'case:delete:own',
  CASE_ASSIGN: 'case:assign',

  // Document Permissions
  DOCUMENT_UPLOAD: 'document:upload',
  DOCUMENT_READ_OWN: 'document:read:own',
  DOCUMENT_READ_SHARED: 'document:read:shared',
  DOCUMENT_DELETE_OWN: 'document:delete:own',

  // AI & RAG Permissions
  AI_USE: 'ai:use',
  AI_ADVANCED_RESEARCH: 'ai:advanced_research',
  AI_DRAFT_GENERATE: 'ai:draft_generate',

  // Consultation & Matching Permissions
  CONSULTATION_CREATE: 'consultation:create',
  CONSULTATION_MANAGE: 'consultation:manage',

  // Professional Ecosystem Permissions
  PROFESSIONAL_CONNECT: 'professional:connect',
  MESSAGE_SEND: 'message:send',
  CASE_STUDY_PUBLISH: 'case_study:publish',

  // Verification & Admin Permissions
  VERIFICATION_REQUEST: 'verification:request',
  VERIFICATION_MANAGE: 'verification:manage',
  ADMIN_MANAGE: 'admin:manage',
  AUDIT_LOG_VIEW: 'audit_log:view',
};

const ROLE_PERMISSIONS = {
  CITIZEN: [
    PERMISSIONS.CASE_CREATE,
    PERMISSIONS.CASE_READ_OWN,
    PERMISSIONS.CASE_UPDATE_OWN,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ_OWN,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_DRAFT_GENERATE,
    PERMISSIONS.CONSULTATION_CREATE,
    PERMISSIONS.MESSAGE_SEND,
  ],
  LAW_STUDENT: [
    PERMISSIONS.CASE_READ_OWN,
    PERMISSIONS.CASE_READ_SHARED,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ_OWN,
    PERMISSIONS.DOCUMENT_READ_SHARED,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_ADVANCED_RESEARCH,
    PERMISSIONS.AI_DRAFT_GENERATE,
    PERMISSIONS.PROFESSIONAL_CONNECT,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.VERIFICATION_REQUEST,
  ],
  LAWYER: [
    PERMISSIONS.CASE_READ_OWN,
    PERMISSIONS.CASE_READ_SHARED,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ_OWN,
    PERMISSIONS.DOCUMENT_READ_SHARED,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_ADVANCED_RESEARCH,
    PERMISSIONS.AI_DRAFT_GENERATE,
    PERMISSIONS.CONSULTATION_MANAGE,
    PERMISSIONS.PROFESSIONAL_CONNECT,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.CASE_STUDY_PUBLISH,
    PERMISSIONS.VERIFICATION_REQUEST,
  ],
  LEGAL_ORGANIZATION: [
    PERMISSIONS.CASE_READ_OWN,
    PERMISSIONS.CASE_READ_SHARED,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ_OWN,
    PERMISSIONS.DOCUMENT_READ_SHARED,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_ADVANCED_RESEARCH,
    PERMISSIONS.AI_DRAFT_GENERATE,
    PERMISSIONS.CONSULTATION_MANAGE,
    PERMISSIONS.PROFESSIONAL_CONNECT,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.CASE_STUDY_PUBLISH,
    PERMISSIONS.VERIFICATION_REQUEST,
  ],
  ADMIN: Object.values(PERMISSIONS),
};

const hasPermission = (userRole, requiredPermission) => {
  if (userRole === 'ADMIN') return true;
  const perms = ROLE_PERMISSIONS[userRole] || [];
  return perms.includes(requiredPermission);
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
};
